### ISSUE TITLE
Cannot verify access token: Session Expired

### ISSUE THREAD

**Issue by saurabh-deochake** [saurabh-deochake/comp-networks-project#1]
If we log out from Facebook or try running facebook_graph.py after a gap of a few days, FB api throws following error:

`facebook.GraphAPIError: Error validating access token: Session has expired on Friday, 07-Apr-17 23:00:00 PDT. The current time is Thursday, 13-Apr-17 19:46:27 PDT.`

Need to figure out a way to refresh access token or a workaround to fool FB API in thinking that we never logged out. THINK!

**Comment by risham33** [comment]
Sign in before?

**Comment by saurabh-deochake** [comment]
This is weird @risham33! Because sometimes token expires on its own in a few minutes and sometimes I worked for straight 5 days. Closing this!
